### ISSUE TITLE
macOS feth interface

### ISSUE THREAD

**Issue by theAeon** [mje-nz/ztdns#1]
On macOS 10.13-10.15 due to deprecation of the kernel drivers used to install the zt0 interface, zerotier uses a pair of feth interfaces as described in https://www.zerotier.com/how-zerotier-eliminated-kernel-extensions-on-macos/

the config file does not appear to have a method of handling a feth pair, so my only option is to have it broadcast on all interfaces, which is a bit suboptimal.

**Comment by theAeon** [comment]
might be related to this

https://github.com/uxbh/ztdns/issues/16

**Comment by johannrichard** [comment]
Did you try to just use the `feth` interface that gets the IP address assigned? According to the doc, the second `feth` only exists because of some quirks. In some tests, I had the server running when using the one which has the IP address assigned -- and it wouldn't start if I picked the other one.

From the [post you mention](https://www.zerotier.com/how-zerotier-eliminated-kernel-extensions-on-macos/):

> Our code computes 4-digit numeric IDs based on network IDs (so they’re always the same) and uses IDs below 5000 for the member of the pair that gets IPs assigned and a corresponding ID above 5000 for the member of the pair used for I/O. (Like Linux “veth” devices they must exist in pairs. A single “feth” device doesn’t appear to want to communicate even if injection and packet sampling is local.)

**Comment by theAeon** [comment]
I believe I did try this, and it still refused to work. Granted, the machine has been down for a while and I'm not sure I can test it right now. Hard to say.

**Comment by mje-nz** [comment]
@theAeon Sorry I missed this, I was already doing what @johannrichard suggested (on 10.13) and it works for me.
